/*
FEDERAL UNIVERSITY OF AMAZONAS - UFAM
IE08 - BACHELOR'S IN COMPUTER SCIENCE 
ICC014 - LAB. OF ADVANCED PROGRAMMING - 2019/01
LIST 02 - CHALLENGE 09
STUDENT - MARCOS AVNER PIMENTA DE LIMA

RECURSIVE SQUARE ROOT

TO CALCULATE SQUARE ROOT OF A REAL NUMBER, YOU CAN USE THE ALGORITHM ABOVE:
	
	SQRT(X, Xo, ξ) = Xo IF /(Xo * Xo) - X/ <= ξ, OR SQRT(X, ((Xo * Xo) + X) / 2 * Xo, ξ) OTHERWISE.

WHERE Xo IS AN INITIAL APPROXIMATION OF THE SQUARE ROOT VALUE OF X AND ξ IS AND ADMISSIBLE ERROR (PRECISION).

RECEIVE AS INPUT A UNLIMITED NUMBER OF VALUES OF X, Xo AND ξ, WHERE X IS A INTERGER POSITIVE VALUE, AND Xo,ξ ARE SIMPLE PRECISION POSITIVE FLOATING POINT VALUES.
CALCULATE AND PRINT, WITH 6 DECIMAL PLACES, THE APROXIMATE SQUARE ROOT VALUE.
CONSIDER THAT ξ IS A POSITIVE REAL VALUE GREATER THAN OR EQUAL TO 0.00001.

THE LAST INPUT VALUES SHOULD COTAIN "0 0 0". INGNORE IT!

EXAMPLES
INPUT
25 4 0.01
120 8 0.001
56 10 0.00001
0 0 0

OUTPUT
5.000000
10.954458
7.483315
*/
#include<stdio.h>
#include<stdlib.h>

void sqrtApprox(unsigned int x, float xo, float e) {
	if (((xo*xo) - x) * ((xo*xo) - x) <= (e*e)) {
		printf("%.6f\n", xo);
	}
	else
		sqrtApprox(x, ((xo*xo)+x) / (2*xo), e);
}

int main() {
	unsigned int x;
	float xo, e;
	scanf(" %u %f %f", &x, &xo, &e);
	if (x == 0) {
		return 0;
	}
	sqrtApprox(x, xo, e);
	main();
}